server:
  port: 8888

spring:
  application:
    name: configService
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:configService/src/main/resources/config